Send emails to project groups [WIP]
LordChunk/Project-Agile pull request #156
Opened 2021-06-08 12:23 UTC by LordChunk

## Description
Adds functionality to send emails to project group members.

## User Story Key(s)
- AVANSAGILE-91

## Affected code

### Controllers
- [e.g. HomeController]

### Views
- [e.g. Home/Index]

### Models
- [e.g. Home/Index]

### Areas
- [e.g. Identity/Account/Login]

## Additional context
Add any other context about the pull request here.

# Reviewer's Area

## Reviewer [reviewer's name]
- [ ] Checked code
- [ ] Checked acceptance criteria
- [ ] Checked edge cases

## Reviewer [reviewer's name]
- [ ] Checked code
- [ ] Checked acceptance criteria
- [ ] Checked edge cases

2021-06-08 13:25 UTC, LordChunk commented
Company pagina geeft deze error
![Uploading image.png…]()

2021-06-08 16:10 UTC, GewoonJaap requested changes

2021-06-08 16:10 UTC, GewoonJaap commented on app/Http/Controllers/MailFormatController.php
> +    $request->validate([
Volgens mij hoeft dit niet, omdat dit ook al in de SendMailRequest wordt gedaan.

2021-06-08 16:10 UTC, GewoonJaap commented on resources/views/mailformat/send.blade.php
> -        <div class="alert alert-danger">{{ $message }}</div>
Nu komt er geen error meer als je body niet matcht met de request regels

2021-06-08 16:10 UTC, GewoonJaap commented on resources/views/mailformat/send.blade.php
> -      <div class="alert alert-danger">{{ $message }}</div>
Nu komt er geen error meer als je contacten niet matchten met de request regels

2021-06-08 16:26 UTC, MartijnAmbagtsheer approved these changes

2021-06-08 16:26 UTC, MartijnAmbagtsheer commented on app/Http/Controllers/MailFormatController.php
> +    $projects = Project::all();
Even filteren of een project wel een projectgroep heeft. Staat anders zo slordig.

En misschien dan maken dat je ook de overige projectgroepen kan toevoegen ondanks dat ze niet bij een project zitten. Zo loop je nooit een projectgroep mis.

2021-06-08 16:26 UTC, MartijnAmbagtsheer commented on resources/views/mailformat/send.blade.php
> +  <fieldset>
Ff class="mb-3" toevoegen, anders staat dat versturen knopje zo tegenaan geplakt.

2021-06-08 16:26 UTC, MartijnAmbagtsheer commented on resources/views/mailformat/send.blade.php
>    <a class="btn btn-primary" type="submit" href="#" onclick="showConfirm()" >Versturen</a>
Alle knoppen zit rechts. Is wel netjes als deze ook rechts staat.

2021-06-09 10:14 UTC, LordChunk commented on app/Http/Controllers/MailFormatController.php
> +    $request->validate([
Ik had dit eerst niet en toen kreeg je gewoon 'n confirmation en werd je doorgestuurd

2021-06-09 10:24 UTC, LordChunk commented on resources/views/mailformat/send.blade.php
> +  <fieldset>
```suggestion
  <fieldset class="mb-3">
```
Kan ook zo jongeman 
![FriendsJoeyTribbianiGIF](https://user-images.githubusercontent.com/23651869/121338222-97073a80-c91d-11eb-8ac1-d478b4747387.gif)

2021-06-09 10:49 UTC, GewoonJaap approved these changes

2021-06-09 12:35 UTC, MartijnAmbagtsheer approved these changes

2021-06-09 13:02 UTC, merged