AVANSAGILE-93 Search and sort tables
LordChunk/Project-Agile pull request #157
Opened 2021-06-08 13:10 UTC by GewoonJaap

## Description
Added search and sort functionality to all the pages that have tables.

## User Story Key(s)
- AVANSAGILE-93
- AVANSAGILE-94

## Affected code

### Controllers
- None

### Views
- All index pages

### Models
- None

### Areas
- None

## Additional context
Updated search.js to allow more tables and input fields.

# Reviewer's Area

## Reviewer [Jo🅱️]
- [x] Checked code
- [x] Checked acceptance criteria
- [x] Checked edge cases

## Reviewer [Jeroen]
- [x] Checked code
- [x] Checked acceptance criteria
- [x] Checked edge cases

2021-06-08 13:23 UTC, LordChunk requested changes
Code ziet er goed uit. Zou graag nog iets van een visuele indicatie willen voor de colommen die je nu selecteerd zodat de gebruiker weet op welke colom nu wordt gesorteerd.

Verder kreeg ik deze error bij het inladen van de project pagina. Dit was op Linux, dus zou iets te maken kunnen hebben met hoofdletters oid.
![image](https://user-images.githubusercontent.com/23651869/121192665-72538a00-c86d-11eb-9218-b28528e49ad3.png)

2021-06-08 13:25 UTC, LordChunk commented
Company pagina geeft deze error
![image](https://user-images.githubusercontent.com/23651869/121193066-cfe7d680-c86d-11eb-878a-49f98cb3effb.png)

2021-06-08 13:39 UTC, GewoonJaap commented
> Company pagina geeft deze error
> ![image](https://user-images.githubusercontent.com/23651869/121193066-cfe7d680-c86d-11eb-878a-49f98cb3effb.png)

Admin abuse, je moet op gewoon account, is ook een issue ;)

2021-06-08 13:49 UTC, jeroenvermaat2000 requested changes
Ik sluit mij aan bij wat Job zegt over dat je visueel iets laat zien dat je ziet dat je kan sorteren. 
Een voorbeeld kan zo'n tooltip zijn.

2021-06-08 13:52 UTC, GewoonJaap commented
Ja nee, zal er wel naar kijken. Is idd handig

2021-06-09 09:30 UTC, jeroenvermaat2000 approved these changes
ziet er heel goed uit jaap. gud jop!

2021-06-09 10:07 UTC, LordChunk approved these changes

2021-06-09 10:07 UTC, merged