Feature/excel import AVANSAGILE-2
LordChunk/Project-Agile pull request #162
Opened 2021-06-09 20:24 UTC by MartijnAmbagtsheer

## Description
Teacher can upload an Excelsheet of their contacts.

## User Story Key(s)
- AVANSAGILE-2

## Affected code

### Controllers
-ExcelController

### Views
- Excel/importExcel

### Models
- ContactImport

### Areas
- Contacts

# Reviewer's Area

## Reviewer Job
- [ ] Checked code
- [ ] Checked acceptance criteria
- [ ] Checked edge cases

## Reviewer Jeroen
- [ ] Checked code
- [ ] Checked acceptance criteria
- [ ] Checked edge cases

2021-06-09 21:04 UTC, LordChunk requested changes
Ik zou gewoon de hele /storage folder in de .gitignore zetten (of anders de storage/framework), want nu zitten er allemaal .tmp files in git.

Deze sexy foto moet in de public folder als je die wil bewaren. 
https://github.com/LordChunk/Project-Agile/blob/2c0c9821b00cd347af0b91a1b2fc67f9b6528574/storage/testFiles/wrongFile.png

2021-06-09 21:04 UTC, LordChunk commented on routes/web.php
> +Route::post('excel/import', [\App\Http\Controllers\ExcelController::class, 'importFile'])
ff class importeren zodat hier niet de hele namespace staat

2021-06-10 13:15 UTC, jeroenvermaat2000 requested changes
![image](https://user-images.githubusercontent.com/62993009/121531222-824ea380-c9fe-11eb-939e-05debcfa9e91.png)
Dit krijg ik als ik op "contactpersonen importeren" druk.
Ik ben ingelogd als Tanja

2021-06-10 13:15 UTC, jeroenvermaat2000 commented
Ik had ook alles geupdate en geseed

2021-06-14 20:58 UTC, MartijnAmbagtsheer commented
> Ik had ook alles geupdate en geseed

Ik krijg jouw error niet als ik gewoon vanalles probeer. Ik zal er met je naar gaan kijken samen.

2021-06-17 18:24 UTC, LordChunk approved these changes
Wow mooie code!

2021-06-17 18:25 UTC, LordChunk approved these changes

2021-06-17 19:44 UTC, jeroenvermaat2000 approved these changes

2021-06-17 19:47 UTC, LordChunk approved these changes

2021-06-17 19:54 UTC, jeroenvermaat2000 approved these changes

2021-06-17 19:55 UTC, merged