AVANSAGILE-59 Show projects on contact page
LordChunk/Project-Agile pull request #163
Opened 2021-06-10 07:53 UTC by Nyekyoo

## Description
Show projects on contact page 

## User Story Key(s)
- AVANSAGILE-59

## Affected code

### Controllers
- ContactController

### Views
- Contact/show

### Models
- NA

### Areas
- Contacts

## Additional context
Add any other context about the pull request here.

# Reviewer's Area

## Reviewer [Jaap]
- [ ] Checked code
- [ ] Checked acceptance criteria
- [ ] Checked edge cases

## Reviewer [Job]
- [ ] Checked code
- [ ] Checked acceptance criteria
- [ ] Checked edge cases

2021-06-10 08:07 UTC, GewoonJaap commented on app/Http/Controllers/ContactController.php
> +    foreach ($contact->projectGroups()->get() as $key => $value) {
```suggestion
    foreach ($contact->projectGroups()->get() as $value) {
```

2021-06-10 08:08 UTC, GewoonJaap submitted a review, later dismissed

2021-06-10 08:18 UTC, GewoonJaap submitted a review, later dismissed

2021-06-11 10:09 UTC, mftver requested changes

2021-06-11 10:09 UTC, mftver commented on app/Http/Controllers/ContactController.php
> +      ->with('contact', $contact)
dit kan ook met compact

2021-06-11 10:10 UTC, LordChunk requested changes

2021-06-11 10:34 UTC, Nyekyoo commented on app/Http/Controllers/ContactController.php
> +    }
Fixed

2021-06-11 11:51 UTC, GewoonJaap approved these changes

2021-06-15 10:56 UTC, LordChunk approved these changes

2021-06-15 18:11 UTC, merged