Redesign several aspects of the design for a better first impression
LordChunk/Project-Agile pull request #164
Opened 2021-06-10 07:55 UTC by Nyekyoo

## Description
Redesign several aspects of the design for a better first impression

## User Story Key(s)
- None

## Affected code

### Controllers
- NA

### Views
- Home
- Layout/navigation

### Models
- NA

### Areas
- Design

## Additional context
Add any other context about the pull request here.

# Reviewer's Area

## Reviewer [reviewer's name]
- [ ] Checked code
- [ ] Checked acceptance criteria
- [ ] Checked edge cases

## Reviewer [reviewer's name]
- [ ] Checked code
- [ ] Checked acceptance criteria
- [ ] Checked edge cases

2021-06-10 08:07 UTC, MartijnAmbagtsheer requested changes

2021-06-10 08:07 UTC, MartijnAmbagtsheer commented on resources/views/layouts/navigation.blade.php
> +    <a class="avans-menu-user" href="{{ route('dashboard') }}" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Druk hier om naar de home pagina te gaan"><img src="{{ URL::to('/') }}/img/lo
..avans-menu-user kan je beter doen met een .container-fluid want die margin aan de zijkanten zorgt voor een horizontal scrollbalk als je beetje inzoomt

2021-06-10 08:07 UTC, MartijnAmbagtsheer commented on resources/views/layouts/navigation.blade.php
> +        <a href="{{ route('project.index') }}"><li>Projecten</li></a>
Bij hover misschien geen blauwe, maar donkerrode kleur. Die geeft contrast, maar is minder 'in your face'

2021-06-10 08:07 UTC, MartijnAmbagtsheer commented on resources/views/home/index.blade.php
> +<div class="avans-split">
Maak dit even met een d-flex of een col-sm-XX want nu werkt dit niet op mobiel

2021-06-10 08:21 UTC, GewoonJaap commented on resources/css/avans.css
> +  margin: 0px;
```suggestion
  margin: 0;
```

2021-06-10 08:21 UTC, GewoonJaap commented on resources/css/avans.css
> +  padding: 0px;
```suggestion
  padding: 0;
```

2021-06-10 08:22 UTC, GewoonJaap commented on resources/css/avans.css
> +  margin: 0px 2px;
```suggestion
  margin: 0 2px;
```

2021-06-10 08:22 UTC, GewoonJaap commented on resources/css/avans.css
> +  padding: 0px 100px;
```suggestion
  padding: 0 100px;
```

2021-06-10 08:25 UTC, GewoonJaap reviewed
![image](https://user-images.githubusercontent.com/33700526/121491165-017bb180-c9d6-11eb-8b3a-a437be359405.png)
Op 1080P zijn er paar kleine foutjes:
- Logo wordt ingedrukt komt wss door `px`
- Scrollbalk om naa rechts/links te scrollen
- Actiepunt aanmaken knop zit beetje in de tekst gedrukt
- Actiepunten lijst is heel lang

Voor de rest ziet het er wel echt goed uit 👍

2021-06-10 11:24 UTC, GewoonJaap requested changes

2021-06-10 11:24 UTC, GewoonJaap commented on resources/views/home/index.blade.php
> +        echo strtok(Auth::user()->name, " ");
Kan dit niet met laravel templating?

2021-06-10 11:35 UTC, Nyekyoo commented on resources/views/home/index.blade.php
> +        echo strtok(Auth::user()->name, " ");
Yes, fixed

2021-06-11 11:44 UTC, GewoonJaap submitted a review, later dismissed

2021-06-17 20:18 UTC, MartijnAmbagtsheer submitted a review, later dismissed

2021-06-17 21:44 UTC, MartijnAmbagtsheer submitted a review, later dismissed

2021-06-18 07:36 UTC, GewoonJaap reviewed
![image](https://user-images.githubusercontent.com/33700526/122524632-a91d6300-d018-11eb-93fc-cfd39a8e07a2.png)
Op een 1080P scherm is het uitklapmenu niet volledig zichtbaar, zit deels achter de scroll balk

2021-06-18 08:35 UTC, MartijnAmbagtsheer approved these changes

2021-06-18 09:35 UTC, GewoonJaap approved these changes

2021-06-18 09:35 UTC, merged