M to m relations projectgroup project
LordChunk/Project-Agile pull request #166
Opened 2021-06-10 11:12 UTC by marijnkieboom

## Description
De relatie tussen de projecten en de projectgroepen was eerst een 1-op-meer, en met deze PR is dat een meer-op-meer geworden.

## User Story Key(s)
- AVANSAGILE-92

## Affected code
een migratie is toegevoegd voor de koppeltabel in de database, bij het model van het project als van de projectgroep is een functie toegevoegd om de gekoppelde objecten op te vragen.

### Controllers
- De ProjectController
- De ProjectGroupController

### Views
- Project: Form
- ProjectGroup: Form, show

### Models
- Project
- Projectgroep

### Areas
- Projecten onderhouden

## Additional context
Add any other context about the pull request here.

# Reviewer's Area

## Reviewer [reviewer's name]
- [ ] Checked code
- [ ] Checked acceptance criteria
- [ ] Checked edge cases

## Reviewer [reviewer's name]
- [ ] Checked code
- [ ] Checked acceptance criteria
- [ ] Checked edge cases

2021-06-10 11:23 UTC, LordChunk requested changes
Paar kleine opmerkingen maar ziet er voor de rest goed uit

2021-06-10 11:23 UTC, LordChunk commented on app/Http/Controllers/ProjectController.php
> +      $project->projectgroups()->attach($newProjectGroup);
Je kan die sync boven weglaten en hier gewoon alles syncen op IDs

2021-06-10 11:23 UTC, LordChunk commented on app/Http/Controllers/ProjectGroupController.php
> +      $projectgroup->projects()->attach($newProject);
Je kan die sync boven weglaten en hier gewoon alles syncen op IDs

2021-06-10 11:23 UTC, LordChunk commented on database/migrations/2021_06_08_203109_projectgroup_has_project.php
> +        });
Deze hebben nu geen onDelete constraints. Ik geloof dat de andere pivot tables dat wel hebben

2021-06-11 10:25 UTC, jeroenvermaat2000 requested changes

2021-06-11 10:25 UTC, jeroenvermaat2000 commented on resources/js/app.js
> +// };
gecommende code

2021-06-11 11:15 UTC, jeroenvermaat2000 approved these changes

2021-06-17 12:45 UTC, jeroenvermaat2000 submitted a review, later dismissed

2021-06-17 14:33 UTC, LordChunk requested changes
Krijg deze error als ik alle projecten verwijder van een projectgroep.
![image](https://user-images.githubusercontent.com/23651869/122416594-26999280-cf89-11eb-88d1-c80ae324ea14.png)

Krijg deze error als ik geen contacten selecteer op de edit pagina
![image](https://user-images.githubusercontent.com/23651869/122416759-47fa7e80-cf89-11eb-85e8-920baebbaec9.png)

Geen randvoorwaarde maar wel onhandig. Als ik meerdere projecten koppel zie ik dit niet op de overzichtspagina.

2021-06-17 17:35 UTC, LordChunk approved these changes

2021-06-17 17:36 UTC, LordChunk approved these changes

2021-06-17 19:42 UTC, jeroenvermaat2000 approved these changes

2021-06-18 07:02 UTC, jeroenvermaat2000 approved these changes

2021-06-18 08:09 UTC, LordChunk approved these changes

2021-06-18 08:15 UTC, merged