AVANSAGILE-89 Change & Forgot Password
LordChunk/Project-Agile pull request #171
Opened 2021-06-15 14:50 UTC by GewoonJaap

## Description
Added the ability to change your password in case you forgot it, and to change it when logged in.

## User Story Key(s)
- AVANSAGILE-89

## Affected code

### Controllers
- ProfileController

### Views
- Profile.Form
- Profile.Manage

### Areas
- Login page, Added profile page

## Additional context
Add any other context about the pull request here.

# Reviewer's Area

## Reviewer [Job]
- [x] Checked code
- [x] Checked acceptance criteria
- [x] Checked edge cases

## Reviewer [Martijn]
- [x] Checked code
- [x] Checked acceptance criteria
- [x] Checked edge cases

2021-06-16 06:58 UTC, MartijnAmbagtsheer requested changes
![image](https://user-images.githubusercontent.com/63644928/122172273-e4852980-ce80-11eb-9a7d-c4fd0c37644e.png)
Wil je als ik mijn email heb ingevuld mij ook gewoon terugleiden naar het beginscherm? Net zoals je hierboven doet zodra ik mijn wachtwoord heb gereset. Nu loop je dood in de applicatie.

2021-06-16 07:13 UTC, GewoonJaap commented
> Wil je als ik mijn email heb ingevuld mij ook gewoon terugleiden naar het beginscherm? Net zoals je hierboven doet zodra ik mijn wachtwoord heb gereset. Nu loop je dood in de applicati

Oh zo, dus als je je wachtwoord bent vergeten, deze reset, wordt je automatisch ingelogd en naar het home scherm gestuurd?

2021-06-16 07:23 UTC, MartijnAmbagtsheer approved these changes

2021-06-17 12:05 UTC, LordChunk approved these changes

2021-06-17 12:06 UTC, merged